import { useRef,useState } from 'react'
import { FileText,Trash2,Upload } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { uploadDocument } from '../../api/documents'
import { loadSample } from '../../api/reviews'
import { useReviewStore } from '../../stores/reviewStore'

const allowed=['pdf','txt','md']
export function UploadPanel(){const input=useRef<HTMLInputElement>(null);const navigate=useNavigate();const setReview=useReviewStore(s=>s.setReview);const [file,setFile]=useState<File|null>(null);const [error,setError]=useState('');const [progress,setProgress]=useState<{percent:number;stage:string}|null>(null)
 const choose=(next?:File)=>{setError('');if(!next)return;const ext=next.name.split('.').pop()?.toLowerCase();if(!ext||!allowed.includes(ext)){setError('Upload a PDF, TXT, or Markdown document.');return}if(next.size===0){setError('The selected file is empty.');return}if(next.size>20*1024*1024){setError('Documents must be 20 MB or smaller.');return}setFile(next)}
 const submit=async()=>{if(!file)return;try{const review=await uploadDocument(file,(percent,stage)=>setProgress({percent,stage}));setReview(review);navigate(`/reviews/${review.document.id}`)}catch(reason){setError(reason instanceof Error?reason.message:'Upload failed.')}finally{setProgress(null)}}
 const sample=async()=>{try{const review=await loadSample('supported');setReview(review);navigate(`/reviews/${review.document.id}`)}catch(reason){setError(reason instanceof Error?reason.message:'Could not load the sample.')}}
 return <><section className="upload-panel upload-drop" aria-labelledby="upload-title" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();choose(e.dataTransfer.files[0])}}><div className="upload-icon">{file?<FileText size={20}/>:<Upload size={20}/>}</div><div><h2 id="upload-title">{file?file.name:'Start a new review'}</h2><p>{file?`${(file.size/1024).toFixed(1)} KB selected`:'Drop a document here or browse from your computer.'}</p></div><div className="button-row">{file?<><button className="button button--primary" onClick={submit} disabled={!!progress}>{progress?'Processing…':'Upload document'}</button><button className="icon-button" aria-label="Remove selected file" onClick={()=>setFile(null)}><Trash2 size={16}/></button></>:<><button className="button button--primary" onClick={()=>input.current?.click()}>Browse files</button><button className="button button--secondary" onClick={sample}>Try sample review</button></>}<input ref={input} hidden type="file" accept=".pdf,.txt,.md,application/pdf,text/plain,text/markdown" onChange={e=>choose(e.target.files?.[0])}/></div><div className="upload-meta"><span>PDF, TXT, MD</span><span>Maximum size: 20 MB</span></div>{progress&&<div className="progress" aria-live="polite"><span style={{width:`${progress.percent}%`}}/><small>{progress.stage==='extracting'?'Extracting and indexing document':'Uploading document'} — {progress.percent}%</small></div>}</section>{error&&<p className="form-error" role="alert">{error}</p>}</>}

